d2cmigration/api/urls.py
from api.views import *
from django.urls import path

urlpatterns = [
    path('',Dashboard.as_view(),name='dashboard'),
    # Basic
    path('district/<int:state_code>/',get_district_list,name='district_list'),
    path('police_code/<int:state_code>/<int:district_code>/',get_police_station_list,name='pstation_list'),
    # Migration
    path('migration/',Migration_Initial_HTML_Handler.as_view(),name='migration'),
    path('migration/cancle/<str:pk>/',Migration_Cancle_HTML_Handler.as_view(),name='migration_batch_cancle'),# History PK
    path('migration/authentication/<int:pk>/',Migration_Auth_Handler.as_view(),name='migration_batch_auth'), # Pk=History PK
    path('migration/details/<int:pk>/',Migration_Batch_Details.as_view(),name='migration_batch_details'), # Pk=History PK
    path('migration/fir_details/<int:pk>/',Migration_FIR_Details_Handler.as_view(),name='migration_batch_fir_list'), # Pk=History PK
    path('migration/start/<int:pk>/',Migration_START_Handler.as_view(),name='migration_start'), # Pk=History PK
    path('migration/stop/<int:pk>/',Migration_STOP_Handler.as_view(),name='migration_stop'), # Pk=History PK
    path('migration/log_file/<int:pk>/<int:line_number>/',Migration_Log_File_Reader_Handler.as_view(),name='migration_batch_fir_list'), # Pk=History PK
    path('migration/history/',Migration_History_Handler.as_view(),name='migration_history'), # Pk=History PK
    path('migration/details/<int:pk>/<str:history>/',Migration_Batch_Details.as_view(),name='migration_history_details'), # Pk=History PK
    # RollBack
    path('rollback/',RollBack_Initial_HTML_Handler.as_view(),name='rollback'),
    path('rollback/batch_fir/<str:batch_sr_num>/',RollBack_GET_Migration_Batch_FIR_Details_Handler.as_view(),name='rollback_get_migration_batch_fir_list'),
    path('rollback/get_migration_single_fir_details/',RollBack_GET_Migration_SINGLE_FIR_Details_Handler.as_view(),name='rollback_get_migration_single_fir_list'),
    path('rollback/cancle/<str:pk>/',RollBack_Cancle_HTML_Handler.as_view(),name='rollback_cancle'),
    path('rollback/authentication/<int:pk>/',RollBack_Auth_Handler.as_view(),name='rollback_auth'), # Pk=History PK
    path('rollback/details/<int:pk>/',RollBack_Details.as_view(),name='rollback_details'), # Pk=History PK
    path('rollback/r_fir_details/<int:pk>/',RollBack_FIR_Batch_List.as_view(),name='rollback_fir_details'), # Pk=History PK
    path('rollback/log_file/<int:pk>/<int:line_number>/',RollBack_Log_Reader_Handler.as_view(),name='rollback_log_reader'), # Pk=History PK
    path('rollback/start/<int:pk>/',RollBack_START_Handler.as_view(),name='rollback_start'), # Pk=History PK
    path('rollback/stop/<int:pk>/',RollBack_STOP_Handler.as_view(),name='rollback_stop'), # Pk=History PK
    path('rollback/history/',RollBack_History_Handler.as_view(),name='rollback_history'),
    path('rollback/history/<int:pk>/<str:history>/',RollBack_Details.as_view(),name='rollback_history_details'), # Pk=History PK
    

]

d2cmigration/d2cmigration/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
from .views import *
from .api_decorator import *
from decorator_include import decorator_include



urlpatterns = [
    path('login/',Login.as_view(),name='login'),
    path('logout/',Logout.as_view(),name='logout'),
    path('',decorator_include(api_login_required,'api.urls',)),
]

d2cmigration/api/models.py
from django.db import models

# Create your models here.

d2cmigration/api/models/migration.py
from django.db import models
from django.contrib.auth.models import User
'''
Status Code 
0: Created
1: Running
2. Success
3. Failed
4. Cancle
5. Abort
'''

# Create your models here.
class Migration_User(models.Model):
	username = models.CharField(db_column='USERNAME',max_length=150,unique=True)
	is_admin = models.IntegerField(db_column='IS_ADMIN',default=0)
	is_staff = models.IntegerField(db_column='IS_STAFF',default=0)
	is_active = models.IntegerField(db_column='IS_ACTIVE',default=0)
	state = models.IntegerField(db_column='STATE_CD',default=0)
	district = models.IntegerField(db_column='DISTRICT_CD',default=0)
	police_station = models.IntegerField(db_column='POLICE_STATION_CD',default=0)
	can_migrate = models.IntegerField(db_column='CAN_MIGRATE',default=0)
	can_rollback = models.IntegerField(db_column='CAN_ROLLBACK',default=0)
	can_test = models.IntegerField(db_column='CAN_TEST',default=0)
	create_time = models.DateTimeField(db_column='CREATE_TIME', blank=True, null=True)  # Field name made lowercase.
	created_by = models.CharField(db_column='CREATED_BY',max_length=150)
	activate_by = models.CharField(db_column='ACTIVATE_BY',max_length=150,blank=True, null=True)
	activate_on = models.DateTimeField(db_column='ACTIVATE_ON', blank=True, null=True)  # Field name made lowercase.
	deactivate_by = models.CharField(db_column='DEACTIVATE_BY',max_length=150,blank=True, null=True)
	deactivate_on = models.DateTimeField(db_column='DEACTIVATE_ON', blank=True, null=True)  # Field name made lowercase.

	class Meta:
		db_table = 't_migration_user'

	def __str__(self):
		return self.username

class Migration_User_Login_Activity(models.Model):
	username = models.CharField(db_column='USERNAME',max_length=150)
	login_time = models.DateTimeField(db_column='LOGIN_TIME')  # Field name made lowercase.
	logout_time = models.DateTimeField(db_column='LOGOUT_TIME', blank=True, null=True)  # Field name made lowercase.

	class Meta:
		managed = True
		db_table = 't_migration_user_login_activity'

	def __str__(self):
		return self.username

class Migration_Rollback_Process(models.Model):
	'''
	0: Queue
	1: Running
	2: Stop
	'''
	type_of_program = (
		('M','Migration'),
		('R','Rollback'),
		)
	history_pk = models.IntegerField(db_column='HISTORY_PK',unique=True)
	program_of_type = models.CharField(db_column='PROGRAM_OF_TYPE', max_length=1,choices=type_of_program)
	add_time = models.DateTimeField(db_column='ADD_TIME')
	start_time = models.DateTimeField(db_column='START_TIME', blank=True, null=True)
	status =  models.IntegerField(db_column='STATUS',default=0)

	
	class Meta:
		db_table = 't_migration_rollback_process'

	def __str__(self):
		return self.batch_sr_num

class TMigration_Batch_Details(models.Model):
	status_current = (
		('C','Created'),
		('CN','Cancle'),
		('S','Success'),
		('F','Failed'),
		('A','Abort'),
		('R','Rollback'),
		('PR','Partial Rollback')
		)
	batch_sr_num = models.CharField(db_column='BATCH_SR_NUM', max_length=100,unique=True)
	fir_sr_count = models.IntegerField(db_column='FIR_SR_COUNT')
	user = models.CharField(db_column='USER', max_length=100)
	failed_reason = models.TextField(db_column='FAILED_REASON',blank=True,null=True)
	is_running = models.IntegerField(db_column='IS_RUNNING',default=0)
	create_time = models.DateTimeField(db_column='CREATE_TIME', blank=True, null=True)  # Field name made lowercase.
	start_time = models.DateTimeField(db_column='START_TIME', blank=True, null=True)  # Field name made lowercase.
	complete_time = models.DateTimeField(db_column='COMPLETE_TIME', blank=True, null=True)  # Field name made lowercase.
	current_status = models.CharField(db_column='CURRENT_STATUS', max_length=2,choices=status_current,default='C')
	

	class Meta:
		db_table = 't_migration_batch_details'

	def __str__(self):
		return self.batch_sr_num

class TMigration_Batch_History(models.Model):
	type_of_program = (
		('M','Migration'),
		('R','Rollback'),
		)
	type_of_method = (
		('B','Batch Wise'),
		('T','Table Wise'),
		('F','FIR Wise')
		)

	batch_sr_num = models.TextField(db_column='BATCH_SR_NUM')
	program_of_type = models.CharField(db_column='PROGRAM_OF_TYPE', max_length=2,choices=type_of_program)
	method_of_type = models.CharField(db_column='METHOD_OF_TYPE', max_length=2,choices=type_of_method)
	status = models.IntegerField(db_column='STATUS',default=0)
	user = models.CharField(db_column='USER', max_length=100)
	cancle_user = models.CharField(db_column='CANCLE_USER', max_length=100)
	auth_count = models.IntegerField(db_column='AUTH_COUNT',default=0)
	failed_reason = models.TextField(db_column='FAILED_REASON',blank=True,null=True)
	create_time = models.DateTimeField(db_column='CREATE_TIME', blank=True, null=True)  # Field name made lowercase.
	rollback_reason = models.CharField(db_column='ROLLBACK_REASON', max_length=100,blank=True,null=True)
	rollback_fir_count = models.IntegerField(db_column='ROLLBACK_FIR_COUNT',null=True,blank=True)
	is_auth = models.IntegerField(db_column='IS_AUTH',default=0)
	start_time = models.DateTimeField(db_column='START_TIME', blank=True, null=True)  # Field name made lowercase.
	complete_time = models.DateTimeField(db_column='COMPLETE_TIME', blank=True, null=True)  # Field name made lowercase.

	class Meta:
		db_table = 't_migration_batch_history'
		
	def __str__(self):
		return (self.batch_sr_num)

class TMigration_Batch_FIR_Details(models.Model):
	status_current = (
		('N','NONE'),
		('C','CANCLE'),
		('S','Success'),
		('F','Failed'),
		('A','Abort'),
		('R','Rollback')
		)
	fir_reg_num = models.CharField(db_column='FIR_REG_NUM', max_length=100)
	state_cd = models.IntegerField(db_column='STATE_CD')  # Field name made lowercase.
	district_cd = models.IntegerField(db_column='DISTRICT_CD')  # Field name made lowercase.
	ps_cd = models.IntegerField(db_column='PS_CD')  # Field name made lowercase.
	reg_year = models.IntegerField(db_column='REG_YEAR')  # Field name made lowercase.
	fir_srno = models.IntegerField(db_column='FIR_SRNO')  # Field name made lowercase.
	batch_sr_num = models.CharField(db_column='BATCH_SR_NUM', max_length=100)
	create_time = models.DateTimeField(db_column='CREATE_TIME', blank=True, null=True)  # Field name made lowercase.
	start_time = models.DateTimeField(db_column='START_TIME', blank=True, null=True)  # Field name made lowercase.
	complete_time = models.DateTimeField(db_column='COMPLETE_TIME', blank=True, null=True)  # Field name made lowercase.
	current_status = models.CharField(db_column='CURRENT_STATUS', max_length=2,choices=status_current,default='N')
	rollback_time = models.DateTimeField(db_column='ROLLBACK_TIME', blank=True, null=True)  # Field name made lowercase.
	rollback_user = models.CharField(db_column='ROLLBACK_USER', max_length=100,blank=True,null=True)
	rollback_reason = models.TextField(db_column='ROLLBACK_REASON',blank=True,null=True)
	failed_reason = models.TextField(db_column='FAILED_REASON',blank=True,null=True)

	class Meta:
		db_table = 't_migration_batch_number_details'

	def __str__(self):
		return str(self.batch_sr_num)


class TRollBack_Batch_Details(models.Model):
	'''
	Status Code 
	0: Created
	2. Success
	3. Failed
	4. Cancle
	5. Abort
	'''

	rollback_id = models.IntegerField(db_column='ROLLBACK_ID')
	batch_sr_num = models.CharField(db_column='BATCH_SR_NUM', max_length=100)
	fir_reg_num = models.CharField(db_column='FIR_REG_NUM', max_length=100)
	username = models.CharField(db_column='USERNAME', max_length=100)
	create_time = models.DateTimeField(db_column='CREATE_TIME', blank=True, null=True)  # Field name made lowercase.
	start_time = models.DateTimeField(db_column='START_TIME', blank=True, null=True)  # Field name made lowercase.
	complete_time = models.DateTimeField(db_column='COMPLETE_TIME', blank=True, null=True)  # Field name made lowercase.
	status =  models.IntegerField(db_column='STATUS',default=0)
	failed_reason = models.TextField(db_column='FAILED_REASON',blank=True,null=True)
	class Meta:
		db_table = 't_rollback_batch_details'

	def __str__(self):
		return self.rollback_id

d2cmigration/api/views.py
from django.shortcuts import render

# Create your views here.

d2cmigration/api/views/base.py
"""
Description : All Import Package
"""
import functools

from django.contrib.auth.decorators import user_passes_test
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect


# Basic Package
from django.contrib import messages

#File Read Package
from django.conf import settings
import os
MIGRATE_LOG_PATH = os.path.join(settings.BASE_DIR,'logs','migration')

#ALL DATABASE
from django.db import transaction, IntegrityError
from api.models import *

MIGRATION_DATABASE = 'migration'
SOURCE_DATABASE = 'source'
DESTINATION_DATABASE = 'destination'


#Templete Package 
from django.views import View
from django.shortcuts import render, redirect
from django.http import HttpResponse 
import json

# Database Package Import 

# Logger 
import logging
logger = logging.getLogger('logfile')



# Local TimeStamp
import datetime
import pytz
UTC = pytz.utc
India_current_time = pytz.timezone('Asia/Kolkata')

d2cmigration/api/templates/api/migration/m_auth.html
{% extends 'api/base.html' %}
{% load static %}
{% load tz %}
{% block title %}D2C Migration: Migration Verification{% endblock title %}
{% block css %}{% endblock css%}
{% block userflex %}	
{% endblock userflex %}
{% block content %}
<div class="app-content content">
	<div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
    	<div class="content-body">
    		<div class="card">
    			<div class="card-body">
    				<div class='row'>
                        {% if messages %}
                        <div class='col-md-12'>
                            {% for message in messages %}
                                {% if message.tags == 'error' %}
                                <div class="alert alert-danger" role="alert">{{ message }}</div>
                                {% elif message.tags == 'success' %}
                                <div class="alert alert-success" role="alert">{{ message }}</div>
                                {% else %}
                                <div class="alert alert-info" role="alert">{{ message }}</div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        {% endif %}
                        <div class="col-md-12" id='create_batch_div' >      
                            <h6 class="card-title" >D2C Migration : Migration Authentication</h6>
                            <form action="" method="post">
                                {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="password">Password</label><code>**</code>
                                        <input type="password" id="password" class="form-control" name="password" placeholder="Please Enter Password.">
                                        <label><code>**</code>Please Enter Password For Verification</label>
                                        <label><code>**</code>Note: Only 4 Attempt is Allowed.</label>
                                    </div>
                                </div>    
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="migration_method">Method</label><code>**</code>
                                        <select class="custom-select form-control" id="migration_method" name="migration_method" required="">
                                            <option value="F" selected>FIR WISE</option>
                                            <option value="T">TABLE WISE</option>
                                        </select>
                                        <label><code>**</code>Choose Migration Method</label>
                                    </div>
                                </div>    
                            </div>
                            <button class='btn btn-danger' style="float:right;">Verification</button>
                            </form>
    				    </div>
    			    </div>
    		    </div>
    	    </div>
        </div>
    </div>
</div>
{% endblock %}

d2cmigration/api/templates/api/migration/m_details.html
{% extends 'api/base.html' %}
{% load static %}
{% load tz %}
{% block title %}D2C Migration: Start Migration{% endblock title %}
{% block css %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
{% endblock css%}
{% block content %}
<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">    
        <div class="content-body">
        <div class="card">
                <div class="card-body">
                    <div class='row'>
                        <div class='col-md-12'>
                            <div class='col-md-6' style="float: left;">
                                <h6 class="card-title" >D2C Migration : Migration Process</h6>
                                <h7 class="card-title" id='migration_system_message'></h7>
                                <input id='is_ongoing' value='{{history_batch_query_set.status}}'  hidden>
                                <input id='history_pk' value='{{history_batch_query_set.pk}}'  hidden>
                                {% csrf_token %}
                            </div>
                            <div class='col-md-6' style="float: right;">
                                <input id='is_migration_running' value='{{history_batch_query_set.status}}' hidden>
                                <input id='is_queue' value='{{history_batch_query_set.status}}' hidden>
                                <button style="float:right; {% if history_batch_query_set.status == 0 %} {% else %} display:none; {% endif %} " class='btn btn-success' id='migration_action_div_start'>Start Migration</button>   
                                <button style="float:right; {% if history_batch_query_set.status == 1 %} {% else %} display:none; {% endif %} " class='btn btn-danger'  id='migration_action_div_stop' >Stop Migration</button> 
                                <span style="float:right;" id='migration_complete'>
                                    {% if history_batch_query_set.status == 2 %} 
                                    <code style="color:green;font-size: 16px;font-style: italic;">**Migration SuccessFull Complete**</code>
                                    {% elif history_batch_query_set.status == 3 %} 
                                    <code style="font-size: 16px;font-style: italic;">**Migration Failed.**</code>
                                    {% elif history_batch_query_set.status == 4 %} 
                                    <code style="font-size: 16px;font-style: italic;">**Migration Cancle By User.**</code>
                                    {% elif history_batch_query_set.status == 5 %}
                                    <code style="font-size: 16px;font-style: italic;">**Migration Abort By User.**</code>
                                    {% endif %}
                                </span>      
                            </div>
                            
                        </div>
                        <div class='col-md-12' style='margin-top: 20px;'> 
                            <div class="row"> 
                                <div class='col-md-12'>
                                    <button class='btn btn-success' style="float:right; " id='batch_details_hide'>Hide Details</button>
                                    <button class='btn btn-danger' style="float:right; display: none;" id='batch_details_show'>Show Details</button>    
                                    <h6 class="card-title">Migration Batch Details</h6>
                                </div>
                            </div>
                            <div class="col-md-12" id='batch_details'>
                                <div class="row">
                                    <div class="col-md-6">
                                        <span>Migration Batch Sr No :</span>
                                        <span id='batch_sr_num'>{{batch_query_set.batch_sr_num}}</span>
                                    </div>
                                    <div class="col-md-6">
                                        <span>Fir Count :</span>
                                        <span>{{batch_query_set.fir_sr_count}}</span>
                                        <a><span id='show_fir' ><code> Show Details</code></span></a>
                                        <a><span id='hide_fir' style="display:none;"><code>Hide Details</code></span></a>
                                    </div>
                                    <div class="col-md-6">
                                        <span>Migration Batch Current Status :</span>
                                        <span>{{batch_query_set.get_current_status_display}}</span>
                                    </div>
                                    <div class="col-md-6">
                                        <span>Created UserName:</span>
                                        <span>{{history_batch_query_set.user|upper}}</span>
                                    </div>
                                    {% if history_batch_query_set.status == 4 %}
                                    <div class="col-md-6">
                                        <span>Cancle By:</span>
                                        <span>{{history_batch_query_set.cancle_user|upper}}</span>
                                    </div>
                                    {% endif %}
                                    <div class="col-md-6">
                                        <span>Creation Time :</span>
                                        <span>{% localtime on %} {{batch_query_set.create_time|date:'d-m-Y H:i:s'}} {% endlocaltime %}</span>
                                    </div> 
                                    {% if history_batch_query_set.status != 0 and history_batch_query_set.status != 1 %}
                                    <div class="col-md-6">
                                        <span>Status :</span>
                                        <span>{% if history_batch_query_set.status == 2 %}
                                                <code style="color:green">Success</code>
                                            {% elif history_batch_query_set.status == 3 %}
                                               <code>Failed</code>
                                            {% elif history_batch_query_set.status == 4 %}
                                              <code>Cancle</code>
                                            {% elif history_batch_query_set.status == 5 %}
                                                <code>Abort</code>
                                            {% endif %}
                                        </span>
                                    </div>
                                    {% endif %}
                                    {% if history_batch_query_set.status != 0 %}
                                    <div class="col-md-6">
                                        <span>Start Time :</span>
                                        <span>{% localtime on %} {{history_batch_query_set.start_time|date:'d-m-Y H:i:s'}} {% endlocaltime %}</span>
                                    </div>
                                    {% endif %}
                                    {% if history_batch_query_set.status != 0 and history_batch_query_set.status != 1 %}
                                    <div class="col-md-6">
                                        <span>End Time :</span>
                                        <span>{% localtime on %} {{history_batch_query_set.complete_time|date:'d-m-Y H:i:s'}} {% endlocaltime %}</span>
                                    </div>
                                    {% endif %}
                                    <div class="col-md-6">
                                        <span>Migration Method:</span>
                                        <span>{{history_batch_query_set.get_method_of_type_display}}</span>
                                    </div>
                                    {% if history_batch_query_set.status == 3 %}
                                    <div class="col-md-6">
                                        <span>Failed Reason :</span>
                                        <span>{{history_batch_query_set.failed_reason}}</span>
                                    </div>
                                    {% endif %}
                                    <div class="col-md-12" id='fir_details'  style="display:none;margin-top:5px;">
                                        <hr>
                                        <h7 class="card-title">Batch {{history_batch_query_set.batch_sr_num}} FIR Details </h7>
                                        <input id='fir_details_status' value="0" hidden>
                                        <p id='file_details_error'></p>
                                        <div class="table-responsive" id='fir_details_table' style="margin-top: 10px;margin-botton: 10px;">
                                            <table class="table mb-0"  id="fir_list_datatable">
                                                <thead class="thead-dark">
                                                    <tr>
                                                        <th scope="col" width="20">ID</th>
                                                        <th scope="col" width="80">FIR Number</th>
                                                        <th scope="col" width="100">State</th>
                                                        <th scope="col" width="100">District</th>
                                                        <th scope="col" width="100">PS Code</th>
                                                        <th scope="col" width="100">Year</th>
                                                        <th scope="col" width="100">Status</th>
                                                    </tr>
                                                </thead>
                                                <tbody id='fir_details_table_tbody'></tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class='col-md-12' id='migration_logs' {% if history_batch_query_set.status == 0 %} style="display:none;" {% endif %} >
                            <hr>
                            <input id='line_length' value='0'  hidden>
                            <button class='btn btn-success' style="float:right; display: none;" id='logs_details_hide'>Hide logs</button>
                            <button class='btn btn-danger' style="float:right;" id='logs_details_show'>Show logs</button>    
                            <h6 class="card-title">Migrations logs</h6>  
                            <pre id='data_in' style=' display: none; overflow-y: scroll;color:white;background: black;min-height: 100px;max-height:300px; padding-left: 10px;width: 100%;margin-top: 7%;'>
                                
                            </pre>    
                        </div>
                        
                    </div>
                </div>
        </div>
    </div>
    </div>
    
</div>
{% endblock content %}
{% block page_js %}
<script src="{% static 'js/migration/migration.js' %}"></script>
 <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>

<script type="text/javascript">
$(document).ready(function(){
        var is_migration_running = $('#is_migration_running').val();
        if (is_migration_running != 0 && is_migration_running != 4){
            get_migration_log()
        }
    })
</script>

{% endblock page_js%}